name: "build"

on: ["push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup JDK 16"
        uses: "actions/setup-java@v2.2.0"
        with:
          distribution: "temurin"
          java-version: "16"
      - name: "Clean Build"
        run: "./gradlew clean shadowJar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build/libs/PlotSquared-*.jar
